/*TABELAS */ 
CREATE DATABASE ELENCO_CORINTHIANS_2026;

USE ELENCO_CORINTHIANS_2026;

CREATE TABLE JOGADORES(
	IDJOGADOR INT AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	IDADE INT NOT NULL,
	POSICAO VARCHAR(20) NOT NULL,
	NACIONALIDADE VARCHAR (50) NOT NULL,
	N_CAMISA CHAR(2) NOT NULL UNIQUE,
	CONSTRAINT PK_JOGADORES PRIMARY KEY(IDJOGADOR)
);

CREATE TABLE ESTATISTICAS(
	ID_ESTATISTICA INT AUTO_INCREMENT,
	PARTIDAS INT NOT NULL,
	GOLS INT NOT NULL,
	ASSISTENCIAS INT NOT NULL,
	CARTAO_AMARELO INT NOT NULL,
	CARTAO_VERMELHO INT NOT NULL,
	ID_JOGADOR INT NOT NULL UNIQUE,
	CONSTRAINT PK_ESTATISTICAS PRIMARY KEY(ID_ESTATISTICA),
	CONSTRAINT FK_JOGADORES_ESTATISTICAS FOREIGN KEY (ID_JOGADOR) REFERENCES JOGADORES(IDJOGADOR)
);


CREATE TABLE CONTRATO(
	ID_CONTRATO INT AUTO_INCREMENT,
	CONTRATO INT NOT NULL,
	SALARIO DECIMAL (10,2) NOT NULL,
	VALOR_MERCADO DECIMAL (10,2) NOT NULL,
	ID_JOGADOR INT NOT NULL UNIQUE,
	CONSTRAINT PK_CONTRATO PRIMARY KEY(ID_CONTRATO),
	CONSTRAINT FK_JOGADORES_CONTRATO FOREIGN KEY (ID_JOGADOR) REFERENCES JOGADORES(IDJOGADOR)
	);



/*INSERTS TABELA JOGADORES*/

INSERT INTO JOGADORES VALUES(NULL, 'HUGO SOUZA', 27, 'GOLEIRO', 'BRASILEIRO', '1');
INSERT INTO JOGADORES VALUES(NULL, 'FELIPE LONGO', 21, 'GOLEIRO','BRASILEIRO', '40');
INSERT INTO JOGADORES VALUES(NULL, 'KAUÃ CAMARGO', 22, 'GOLEIRO','BRASILEIRO','51');
INSERT INTO JOGADORES VALUES(NULL, 'MATHEUZINHO', 25,'LATERAL-DIREITO','BRASILEIRO','2');
INSERT INTO JOGADORES VALUES(NULL, 'GABRIEL PAULISTA', 35,'ZAGUEIRO','BRASILEIRO','3');
INSERT INTO JOGADORES VALUES(NULL,'ANDRÉ RAMALHO',34,'ZAGUEIRO','BRASILEIRO','5');
INSERT INTO JOGADORES VALUES(NULL,'JOÃO PEDRO',22,'ZAGUEIRO','BRASILEIRO','47');
INSERT INTO JOGADORES VALUES(NULL,'GUSTAVO HENRIQUE',33,'ZAGUEIRO','BRASILEIRO','13');
INSERT INTO JOGADORES VALUES(NULL,'MATHEUS BIDU',27,'LATERAL-ESQUERDO','BRASILEIRO','21');
INSERT INTO JOGADORES VALUES(NULL,'FABRIZIO ANGILERI','LATERAL-ESQUERDO','ARGENTINO','26');
INSERT INTO JOGADORES VALUES(NULL,'HUGO',28,'LATERAL-ESQUERDO','BRASILEIRO','46');
INSERT INTO JOGADORES VALUES(NULL,'BRENO BIDON',21, 'MEIO-CAMPO','BRASILEIRO','7');
INSERT INTO JOGADORES VALUES(NULL,'RODRIGO GARRO',28,'MEIO-CAMPO','ARGENTINO','8');
INSERT INTO JOGADORES VALUES(NULL,'RANIELE',29,'MEIO-CAMPO','BRASILEIRO','19');
INSERT INTO JOGADORES VALUES(NULL,'ALLAN',29,'MEIO-CAMPO','BRASILEIRO','20');
INSERT INTO JOGADORES VALUES(NULL,'CHARLES',30,'MEIO-CAMPO','BRASILEIRO','35');
INSERT INTO JOGADORES VALUES(NULL,'ANDRÉ',20,'MEIO-CAMPO','BRASILEIRO','49');
INSERT INTO JOGADORES VALUES(NULL,'LUIS GUSTAVO',20,'MEIO-CAMPO','BRASILEIRO','54');
INSERT INTO JOGADORES VALUES(NULL,'DIEGUINHO',18,'MEIO-CAMPO','BRASILEIRO','61');
INSERT INTO JOGADORES VALUES(NULL,'JESSE LINGARD',33,'MEIO-CAMPO','INGLÊS','77');
INSERT INTO JOGADORES VALUES(NULL,'ALEX SANTANA',31,'MEIO-CAMPO','BRASILEIRO','80');
INSERT INTO JOGADORES VALUES(NULL,'YURI ALBERTO',25,'ATACANTE','BRASILEIRO','9');
INSERT INTO JOGADORES VALUES(NULL,'MEMPHIS DEPAY',32,'ATACANTE','HOLANDÊS','10');
INSERT INTO JOGADORES VALUES(NULL,'VITINHO',32,'ATACANTE','BRASILEIRO','11');
INSERT INTO JOGADORES VALUES(NULL,'PEDRO RAUL',29,'ATACANTE','BRASILEIRO','18');
INSERT INTO JOGADORES VALUES(NULL,'KAYQUE FERRARI',22,'ATACANTE','BRASILEIRO','31');
INSERT INTO JOGADORES VALUES(NULL,'KAIO',22,'ATACANTE','BRASILEIRO','37');
INSERT INTO JOGADORES VALUES(NULL,'ZAKARIA LABYAD',33,'ATACANTE','MARROQUINHO','52');
INSERT INTO JOGADORES VALUES(NULL,'GUI NEGÃO',19,'ATACANTE','BRASILEIRO','56');
INSERT INTO JOGADORES VALUES(NULL,'KAYQUE',16,'ATACANTE','BRASILEIRO','79');


/*INSERT TABELA ESTATISTICAS*/

INSERT INTO ESTATISTICAS VALUES(NULL, PARTIDAS, GOLS, ASSISTENCIAS,CARTAOAMARELO, CARTAOVERMELHO,IDJOGADOR);