CREATE DATABASE ELENCO_CORINTHIANS_2026;

USE ELENCO_CORINTHIANS_2026;

CREATE TABLE JOGADORES(
	IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	IDADE INT NOT NULL,
	POSICAO VARCHAR(20) NOT NULL,
	NACIONALIDADE VARCHAR (50) NOT NULL,
	N_CAMISA CHAR(2) NOT NULL UNIQUE
);

CREATE TABLE ESTATISTICAS(
	ID_ESTATISTICA INT PRIMARY KEY AUTO_INCREMENT,
	PARTIDAS INT NOT NULL,
	GOLS INT NOT NULL,
	ASSISTENCIAS INT NOT NULL,
	CARTAO_AMARELO INT NOT NULL,
	CARTAO_VERMELHO INT NOT NULL,
	ID_JOGADOR INT NOT NULL UNIQUE,
	FOREIGN KEY (ID_JOGADOR) REFERENCES JOGADORES(IDJOGADOR)
);

CREATE TABLE CONTRATO(
	ID_CONTRATO INT PRIMARY KEY AUTO_INCREMENT,
	CONTRATO INT NOT NULL,
	SALARIO DECIMAL (10,2) NOT NULL,
	VALOR_MERCADO DECIMAL (10,2) NOT NULL,
	ID_JOGADOR INT NOT NULL UNIQUE,
	FOREIGN KEY (ID_JOGADOR) REFERENCES JOGADORES (IDJOGADOR)
);